sudo: required
dist: trusty

before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.37.1/hugo_0.37.1_Linux-64bit.deb && sudo dpkg -i hugo_0.37.1_Linux-64bit.deb

script:
  - echo "OK"

# branches:
#   only:
#   - master

notifications:
  slack: guneysu:g4dUCQCfxQ4tHZziwDMOlU7k
    
before_deploy:
  - hugo
  - tar caf public.tar.gz public/
  - git config --local user.name "$GITHUB_NAME"
  - git config --local user.email "$GITHUB_EMAIL"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  
deploy:
  - provider: surge
    on: develop
    skip_cleanup: true
    project: ./public/
    domain: ahmedseref.surge.sh

  - provider: releases
    on: master
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: public.tar.gz

  - provider: s3
    on: master
    skip_cleanup: true
    access_key_id: $S3_KEY
    secret_access_key: $S3_SECRET
    bucket: $S3_BUCKET
    region: $S3_REGION
    acl: public-read
    local_dir: public