sudo: false # required
dist: trusty

before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.38/hugo_0.38_Linux-64bit.deb && sudo dpkg -i hugo_0.38_Linux-64bit.deb
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install yarn
  - yarn --version
  - cd themes/skeleton
  - yarn install
  - yarn build
  - cd ../../
  
cache:
  directories:
  - themes/skeleton/node_modules
  
script:
  - hugo

notifications:
  slack: guneysu:g4dUCQCfxQ4tHZziwDMOlU7k

before_deploy:
  - hugo
  - tar caf public.tar.gz public/
  - git config --local user.name "$GITHUB_NAME"
  - git config --local user.email "$GITHUB_EMAIL"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  # - provider: surge
  #   skip_cleanup: true
  #   on:
  #     all_branches: true
  #   project: ./public/
  #   domain: ahmedseref.surge.sh

  - provider: releases
    on: master
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: public.tar.gz

  - provider: s3
    on: master
    skip_cleanup: true
    access_key_id: $S3_KEY
    secret_access_key: $S3_SECRET
    bucket: $S3_BUCKET
    region: $S3_REGION
    acl: public-read
    local_dir: public
