baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"

[Params]
AuthorName = "Ahmed "
Description = "Tesla's Awesome Hugo Site"
author = "Nikola Tesla"
Tagline = "Hello, world!"

HomepagePosts = 3

SocialLinks = true

GithubUsername = "guneysus"

HighLightTheme = "github"

UglyURLs =	true

[Author]
name = "Damien Caselli"
homepage = "http://dcsl.li"

