baseURL = "/"
languageCode = "en-us"
theme = "guneysu-blog"
defaultContentLanguage = "tr"
enableEmoji = true

# Set the unicode character used for the "return" link in page footnotes.
footnotereturnlinkcontents = "↩"

pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "bw"
pygmentsUseClasses = true
newContentEditor = "code-insiders"
pygmentsCodeFences = true

preserveTaxonomyNames = true
rssLimit = 30
paginate = 10

DefaultContentLanguage = "tr"
disableLiveReload = false

[Params]
    Description = "Amazon Web Service, .NET, ASP.NET MVC Related posts, articles and ideas"
    AuthorName = "Ahmed Şeref GÜNEYSU"
    Tagline = "⠛⠥⠝⠑⠽⠎⠥⠎ /home/asguneysu"
    Title = "/home/asguneysu"
    Author = "Ahmed Şeref Güneysu"

    HighLightTheme = "github"
    PygmentsTheme = "bw"

[languages]
[languages.en]
    weight = 1

[languages.tr]
    weight = 1

[taxonomies]
    tag = "tags"

[permalinks]
    post = "/post/:slug/"
    page = "/:slug/"

[menu]
    [[menu.main]]
        name = "home"
        title = "home"
        url = "/"
        weight = 0
        pre = '<i class="icon icon-home"> </i>'

    [[menu.main]]
        name = "posts-tr"
        title = "posts"
        url = "/post/"
        weight = 1
        pre = '<i class="icon icon-doc-text"> </i>'
        post = "[tr]"

    [[menu.main]]
        name = "post-en"
        title = "posts"
        url = "/en/post/"
        weight = 2
        pre = '<i class="icon icon-doc-text"> </i>'
        post = "[en]"

    [[menu.main]]
        name = "news"
        title = "news"
        url = "/news/"
        weight = 3
        pre = '<i class="icon icon-newspaper"> </i>'

    [[menu.main]]
        name = "snippet"
        title = "snippets"
        url = "/snippet/"
        weight = 3
        pre = '<i class="icon icon-newspaper"> </i>'

    [[menu.main]]
        name = "tags"
        title = "tags"
        url = "/tags/"
        weight = 4
        pre = "<i class='icon icon-tags'> </i>"



# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
    plainIDAnchors = true
    # See https://github.com/gohugoio/hugo/issues/2424
    hrefTargetBlank = true
    angledQuotes = false
    latexDashes = true
    fractions = true
    extensions =  ["tables", ""]
    titleblock = true

[imaging]
# See https://github.com/disintegration/imaging
# CatmullRom is a sharp bicubic filter which should fit the docs site well with its many screenshots.
# Note that you can also set this per image processing.
resampleFilter = "CatmullRom"

# Default JPEG quality setting. Default is 75.
quality = 75

anchor = "smart"


[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "mydeployment"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
# URL = "gs://<Bucket Name>"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
# URL = "s3://<Bucket Name>?region=<AWS region>"

URL = "s3://blog.guneysu.xyz.s3-website.eu-central-1.amazonaws.com"
# Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
# URL = "azblob://$web"

# You can use a "prefix=" query parameter to target a subfolder of the bucket:
# URL = "gs://<Bucket Name>?prefix=a/subfolder/"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
# cloudFrontDistributionID = <ID>


[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]