baseURL = "/"
languageCode = "en-us"
title = "Ahmed Şeref Güneysu"
theme = "paperbackcustom"

[Params]
Description = "⠛⠥⠝⠑⠽⠎⠥⠎ /home/asguneysu"
Author = "Ahmed Şeref GÜNEYSU"
Tagline = "Hello, world!"

HomepagePosts = 5

SocialLinks = true

GithubUsername = "guneysus"
LinkedinUserName = "guneysu"
# TumblrUserName = "guneysu"

HighLightTheme = "github"

UglyURLs =	false
