baseURL = "/"
languageCode = "en-us"
theme = "guneysu-blog"
defaultContentLanguage = "tr"
enableEmoji = true

# Set the unicode character used for the "return" link in page footnotes.
footnotereturnlinkcontents = "↩"

pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "bw"
pygmentsUseClasses = true
newContentEditor = "code-insiders"
pygmentsCodeFences = true

preserveTaxonomyNames = true
rssLimit = 30
paginate = 10

DefaultContentLanguage = "tr"
disableLiveReload = false

[Params]
    Description = "Amazon Web Service, .NET, ASP.NET MVC Related posts, articles and ideas"
    AuthorName = "Ahmed Şeref GÜNEYSU"
    Tagline = "⠛⠥⠝⠑⠽⠎⠥⠎ /home/asguneysu"
    Title = "/home/asguneysu"
    Author = "Ahmed Şeref Güneysu"

    HighLightTheme = "github"
    PygmentsTheme = "bw"

[languages]
[languages.en]
    weight = 1

[languages.tr]
    weight = 1

[taxonomies]
    tag = "tags"

[permalinks]
    # post = "/post/:year/:month/:slug/" # TODO
    post = "/post/:slug/"
    page = "/:slug/"

[menu]
    [[menu.main]]
        name = "home"
        title = "home"
        url = "/"
        weight = 0
        pre = '<i class="icon icon-home"> </i>'

    [[menu.main]]
        name = "posts-tr"
        title = "posts"
        url = "/post/"
        weight = 1
        pre = '<i class="icon icon-doc-text"> </i>'
        post = "[tr]"

    [[menu.main]]
        name = "post-en"
        title = "posts"
        url = "/en/post/"
        weight = 2
        pre = '<i class="icon icon-doc-text"> </i>'

        post = "[en]"
    [[menu.main]]
        name = "contrib"
        title = "contributions"
        url = "/contributions/"
        weight = 3
        pre = '<i class="icon"> </i>'

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 1

[imaging]
# See https://github.com/disintegration/imaging
# CatmullRom is a sharp bicubic filter which should fit the docs site well with its many screenshots.
# Note that you can also set this per image processing.
resampleFilter = "CatmullRom"

# Default JPEG quality setting. Default is 75.
quality = 85

anchor = "smart"


[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "s3"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
# URL = "gs://<Bucket Name>"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
# URL = "s3://<Bucket Name>?region=<AWS region>"

# URL = "s3://blog.guneysu.xyz.s3-website.eu-central-1.amazonaws.com"
URL = "s3://blog.guneysu.xyz?region=eu-central-1"
# Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
# URL = "azblob://$web"

# You can use a "prefix=" query parameter to target a subfolder of the bucket:
# URL = "gs://<Bucket Name>?prefix=a/subfolder/"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
# cloudFrontDistributionID = <ID>

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=2592000, no-transform, public" # 3600 * 24 * 30
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=2592000, no-transform, public" # 3600 * 24 * 30
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true



[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]