baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[Params]
	# your name to display by the copyright sign
	# default: undefined
	AuthorName = "Ahmed "
	Theme = "vs"

# tagline to show beneath homepage h1
# default: undefined
Tagline = "Hello, world!"

# number of posts to show on index
# default: 10
HomepagePosts = 3

# if set to true, social links will be displayed in the footer
# default: undefined
SocialLinks = true

# default: undefined
GithubUsername = "damiencaselli"

# default: undefined
TwitterUsername = "damiencaselli"

pygmentsStyle = "friendly" # "default" # friendly
pygmentsuseclasses =    true

uglyURLs =	true



