
baseURL = "/"
languageCode = "en-us"
# title = "Ahmed Şeref Güneysu"
# theme = "skeleton"
theme = "guneysu-blog"
# theme = "paperbackcustom"


defaultContentLanguage = "tr"
enableEmoji = true
# Set the unicode character used for the "return" link in page footnotes.
footnotereturnlinkcontents = "↩"

pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "bw"
pygmentsUseClasses = true
newContentEditor = "code-insiders"
pygmentsCodeFences = true

preserveTaxonomyNames = true
# rssLimit = 10
# paginate = 10

DefaultContentLanguage = "tr"
disableLiveReload = false

Title = "/home/asguneysu"

[Params]
    Description = "⠛⠥⠝⠑⠽⠎⠥⠎ /home/asguneysu"
    AuthorName = "Ahmed Şeref GÜNEYSU"
    Tagline = "Hello, world!"

    HomepagePosts = 1

    SocialLinks = true

    GithubUsername = "guneysus"
    LinkedinUserName = "guneysu"
    # TumblrUserName = "guneysu"

    HighLightTheme = "github"
    PygmentsTheme = "bw"



[languages]
[languages.en]
    weight = 1

[languages.tr]
    weight = 1

[taxonomies]
    tag = "tags"

[permalinks]
    post = "/post/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "tags"
    url = "/tags"
    weight = -120

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
    plainIDAnchors = true
    # See https://github.com/gohugoio/hugo/issues/2424
    hrefTargetBlank = true
    angledQuotes = false
    latexDashes = true
    fractions = true
    extensions =  ["tables", ""]
    titleblock = true

[imaging]
# See https://github.com/disintegration/imaging
# CatmullRom is a sharp bicubic filter which should fit the docs site well with its many screenshots.
# Note that you can also set this per image processing.
resampleFilter = "CatmullRom"

# Default JPEG quality setting. Default is 75.
quality = 75

anchor = "smart"