baseURL = "/"
languageCode = "en-us"
title = "Ahmed Şeref Güneysu"

[Params]
Description = "⠛⠥⠝⠑⠽⠎⠥⠎ /home/asguneysu"
Author = "Ahmed Şeref GÜNEYSU"
Tagline = "Hello, world!"

HomepagePosts = 5

SocialLinks = false

GithubUsername = "guneysus"
LinkedinUserName = "guneysu"
TumblrUserName = "guneysu"

HighLightTheme = "github"

UglyURLs =	false
