
baseURL = "/"
languageCode = "en-us"
# title = "Ahmed Şeref Güneysu"
theme = "paperbackcustom"


pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "bw"
pygmentsUseClasses = true
newContentEditor = "code-insiders"
pygmentsCodeFences = true

paginate = 10

DefaultContentLanguage = "tr"


[Params]
Description = "⠛⠥⠝⠑⠽⠎⠥⠎ /home/asguneysu"
Author = "Ahmed Şeref GÜNEYSU"
Tagline = "Hello, world!"

HomepagePosts = 5

SocialLinks = true

GithubUsername = "guneysus"
LinkedinUserName = "guneysu"
# TumblrUserName = "guneysu"

HighLightTheme = "github"
PygmentsTheme = "bw"



[languages]
[languages.en]
weight = 1

[languages.tr]
weight = 1