baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"

[Params]
Description = "⠛⠥⠝⠑⠽⠎⠥⠎ /home/asguneysu"
Author = "Ahmed Şeref GÜNEYSU"
Tagline = "Hello, world!"

HomepagePosts = 3

SocialLinks = true

GithubUsername = "guneysus"
LinkedinUserName = "guneysu"
TumblrUserName = "guneysu"

HighLightTheme = "github"

UglyURLs =	false
