version: '3'

services:

  user-api:
    image: gm-user-api:latest
    build:
      context: .
      dockerfile: user-api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5100
    ports:
      - "5100:5100"


  project-api:
    image: gm-project-api:latest
    build:
      context: .
      dockerfile: project-api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5101
    ports:
      - "5200:5200"


  task-api:
    image: gm-task-api:latest
    build:
      context: .
      dockerfile: task-api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5300
    ports:
      - "5300:5300"

  # gateway:
  #   image: gm-gateway:latest
  #   build:
  #     context: .
  #     dockerfile: Gateway/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:5000
  #   ports:
  #     - "5000:5000"